<?php
/*******************************************************************************
 *
 *   CrystalPHP Framework by Crystal Collective
 *   An open source application development framework for PHP
 *
 *   This file is part of CrystalPHP which is released under the MIT License (MIT)
 *
 *   Copyright (c) 2019 - 2019, Crystal Collective
 *
 *   For the full copyright and license information,
 *   please view the LICENSE file that was distributed with this source code.
 *
 ******************************************************************************/

/**
 * User: Pankaj Vaghela
 * Date: 31-05-2019
 * Time: 15:59
 */

namespace CrystalPHP\Controller;

use CrystalPHP\REST;


define("RT_BASE_API", "rest_api");

/**
 * Class ApiController
 * @package CrystalPHP\Controller
 *
 * @property REST $rest;
 */
class ApiController extends Controller{
	
	/**
	 * @var REST $rest
	 */
	protected $rest;
	protected $error = array();
	protected $data = array();
	
	function init(){
		parent::init();
		$this->rest = new REST;
	}
	
	public function setupPage(){
		/* switch($this->rest->getRequestMethod()){
			 case 'get':
				 return $this->get();
				 break;
			 case 'post':
				 return $this->post();
				 break;
			 case 'put':
				 return $this->put();
				 break;
			 case 'delete':
				 return $this->delete();
				 break;
			 default:
				 $this->rest->sendResponse(405);
				 return null;
				 break;
		 }*/
	}
	
	/**
	 * @throws ControllerException
	 */
	public function pageRender(){
		$this->render();
	}
	
	public function render(){
		parent::render(); // TODO: Change the autogenerated stub
	}
	
	public function dispatch(){
		return parent::dispatch(); // TODO: Change the autogenerated stub
	}
	
	//Abstract Methods
	public function get(){
		$this->rest->sendResponse(405);
		return null;
	}
	
	public function post(){
		$this->rest->sendResponse(405);
		return null;
	}
	
	public function put(){
		$this->rest->sendResponse(405);
		return null;
	}
	
	public function delete(){
		$this->rest->sendResponse(405);
		return null;
	}
}